# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: keys.pb

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='keys.pb',
  package='gadgetStore',
  serialized_pb='\n\x07keys.pb\x12\x0bgadgetStore\"&\n\x06Gadget\x12\x0e\n\x06offset\x18\x01 \x02(\x03\x12\x0c\n\x04size\x18\x02 \x02(\x03\"7\n\x03Key\x12\x0b\n\x03key\x18\x01 \x02(\t\x12#\n\x06gadget\x18\x02 \x02(\x0b\x32\x13.gadgetStore.Gadget\")\n\x07KeyList\x12\x1e\n\x04keys\x18\x01 \x03(\x0b\x32\x10.gadgetStore.Key')




_GADGET = _descriptor.Descriptor(
  name='Gadget',
  full_name='gadgetStore.Gadget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='offset', full_name='gadgetStore.Gadget.offset', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size', full_name='gadgetStore.Gadget.size', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=62,
)


_KEY = _descriptor.Descriptor(
  name='Key',
  full_name='gadgetStore.Key',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='gadgetStore.Key.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gadget', full_name='gadgetStore.Key.gadget', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=64,
  serialized_end=119,
)


_KEYLIST = _descriptor.Descriptor(
  name='KeyList',
  full_name='gadgetStore.KeyList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='keys', full_name='gadgetStore.KeyList.keys', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=121,
  serialized_end=162,
)

_KEY.fields_by_name['gadget'].message_type = _GADGET
_KEYLIST.fields_by_name['keys'].message_type = _KEY
DESCRIPTOR.message_types_by_name['Gadget'] = _GADGET
DESCRIPTOR.message_types_by_name['Key'] = _KEY
DESCRIPTOR.message_types_by_name['KeyList'] = _KEYLIST

class Gadget(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _GADGET

  # @@protoc_insertion_point(class_scope:gadgetStore.Gadget)

class Key(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEY

  # @@protoc_insertion_point(class_scope:gadgetStore.Key)

class KeyList(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _KEYLIST

  # @@protoc_insertion_point(class_scope:gadgetStore.KeyList)


# @@protoc_insertion_point(module_scope)
